services:
  app:
    build: .
    shm_size: '6gb'
    container_name: nti-alias
    ports:
      - 3002:3001
    volumes:
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]