services:
  app:
    build: .
    shm_size: "6gb"
    container_name: cyclegan-pytorch
    ports:
      - 3001:3001
    volumes:
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
